import React, { useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { ExternalLink, Filter, Github, Search, Sparkles } from 'lucide-react';

type Category = 'Generative AI' | 'Scientific AI' | 'Computer Vision' | 'AI Engineering' | 'Cybersecurity' | 'Full Stack';
type Project = { title: string; problem: string; approach: string; category: Category; stack: string[]; features: string[]; github?: string; demo?: string; research?: string };
const categories: Array<'All' | Category> = ['All', 'Generative AI', 'Scientific AI', 'Computer Vision', 'AI Engineering', 'Cybersecurity', 'Full Stack'];
const projects: Project[] = [
  { title: 'AI Interviewer Platform', problem: 'Streamline interview practice and assessment with an AI-led conversational experience.', approach: 'Python backend services, conversational AI, model integration, and structured interview workflows.', category: 'Generative AI', stack: ['Python', 'FastAPI', 'LLMs', 'Conversational AI'], features: ['Voice-oriented workflow', 'Interview orchestration', 'Backend APIs'] },
  { title: 'Scientific AI / Molecular Generation', problem: 'Explore generative approaches for creating and reasoning about molecular structures.', approach: 'Molecular representations and generative modeling concepts for drug-discovery workflows.', category: 'Scientific AI', stack: ['Python', 'RDKit', 'DeepChem', 'Diffusion Models'], features: ['Molecular generation', 'Scaffold conditioning', 'Scientific workflow'] },
  { title: 'CYP Binding Affinity / CYP Modeling', problem: 'Support computational analysis of CYP-related molecular behavior.', approach: 'Machine learning workflows for molecular features, prediction, and model integration.', category: 'Scientific AI', stack: ['Python', 'RDKit', 'DeepChem', 'Molecular Graphs'], features: ['CYP inhibition prediction', 'Binding affinity modeling', 'ADMET context'] },
  { title: 'SIEM Log Analyzer for SSH Threat Detection', problem: 'Surface suspicious activity in Linux authentication logs.', approach: 'Log analysis and security intelligence workflows for identifying SSH threat patterns.', category: 'Cybersecurity', stack: ['Python', 'SIEM', 'Linux Logs', 'MITRE ATT&CK'], features: ['Authentication log analysis', 'Threat indicators', 'AbuseIPDB and VirusTotal context'] },
  { title: 'Fire & Smoke Detection using YOLOv9', problem: 'Detect fire and smoke in visual inputs for safety-oriented monitoring.', approach: 'Object-detection workflow using the YOLOv9 family for computer vision inference.', category: 'Computer Vision', stack: ['Python', 'YOLOv9', 'Computer Vision'], features: ['Visual detection', 'Inference workflow', 'Safety monitoring'] },
  { title: 'AI Healthcare Voice Assistant', problem: 'Provide a voice-driven interface for healthcare-oriented interactions.', approach: 'Conversational AI, speech workflows, and backend integration for guided user experiences.', category: 'Generative AI', stack: ['Python', 'NLP', 'Speech Processing', 'Flask'], features: ['Voice workflow', 'Conversational responses', 'API integration'] },
  { title: 'EXPENX', problem: 'Coordinate shared expenses with a real-time collaborative platform.', approach: 'Full-stack service with real-time synchronization, receipt capture, and payment workflows.', category: 'Full Stack', stack: ['Node.js', 'NestJS', 'PostgreSQL', 'Redis', 'WebSockets'], features: ['Expense splitting', 'OCR receipt capture', 'Real-time synchronization'], github: 'https://github.com/srikruthireddy-pinnapureddy/ExpenX', demo: 'https://expenx-splitting-app.vercel.app/' },
  { title: 'Team Task Manager', problem: 'Manage users, roles, and task lifecycles through a focused backend service.', approach: 'REST APIs, authentication, database design, and service-layer testing.', category: 'AI Engineering', stack: ['Node.js', 'NestJS', 'PostgreSQL', 'REST APIs'], features: ['User management', 'Task workflows', 'Role-based access'], github: 'https://github.com/srikruthireddy-pinnapureddy/team_task_manager_backend' }
];

export function Projects() {
  const [selectedCategory, setSelectedCategory] = useState<'All' | Category>('All');
  const [searchQuery, setSearchQuery] = useState('');
  const visibleProjects = useMemo(() => projects.filter((project) => {
    const text = `${project.title} ${project.problem} ${project.approach} ${project.category} ${project.stack.join(' ')} ${project.features.join(' ')}`.toLowerCase();
    return (selectedCategory === 'All' || project.category === selectedCategory) && text.includes(searchQuery.toLowerCase());
  }), [searchQuery, selectedCategory]);

  return <section className="px-6 py-20" id="projects"><div className="mx-auto max-w-7xl">
    <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-10 text-center"><p className="mb-3 font-mono text-sm uppercase tracking-[0.25em] text-cyan-300">Selected Work</p><h2 className="mb-5 bg-gradient-to-r from-cyan-300 to-blue-400 bg-clip-text text-4xl font-bold text-transparent md:text-5xl">Featured AI Projects</h2><p className="mx-auto max-w-3xl text-lg text-gray-400">AI systems, scientific workflows, computer vision, security automation, and the backend services that connect them to real users.</p></motion.div>
    <div className="mb-8 grid gap-4 rounded-2xl border border-gray-700/60 bg-gray-900/45 p-4 lg:grid-cols-[1fr_auto]"><label className="flex items-center gap-3 rounded-xl border border-gray-700/50 bg-gray-950/40 px-4 py-3"><Search className="text-cyan-300" size={18} /><span className="sr-only">Search projects</span><input value={searchQuery} onChange={(event) => setSearchQuery(event.target.value)} placeholder="Search projects, tools, or domains" className="w-full bg-transparent text-white outline-none placeholder:text-gray-500" /></label><label className="flex items-center gap-2 text-gray-400"><Filter size={18} /><span className="sr-only">Filter projects</span><select value={selectedCategory} onChange={(event) => setSelectedCategory(event.target.value as 'All' | Category)} className="rounded-lg border border-gray-700/50 bg-gray-950/60 px-3 py-2 text-gray-300">{categories.map((category) => <option key={category}>{category}</option>)}</select></label></div>
    <div className="grid items-stretch gap-6 md:grid-cols-2 lg:grid-cols-3">{visibleProjects.map((project, index) => <ProjectCard key={project.title} project={project} index={index} />)}</div>
  </div></section>;
}

function ProjectCard({ project, index }: { project: Project; index: number }) {
  return <motion.article initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.04 }} className="flex h-full flex-col rounded-2xl border border-gray-700/60 bg-gray-900/75 p-6 backdrop-blur-sm transition-colors hover:border-cyan-400/50"><div className="mb-5 flex items-start justify-between gap-3"><Sparkles className="text-cyan-300" size={22} /><span className="rounded-full border border-cyan-400/20 bg-cyan-500/10 px-3 py-1 text-xs text-cyan-100">{project.category}</span></div><h3 className="text-xl font-bold text-white">{project.title}</h3><p className="mt-3 text-sm leading-relaxed text-gray-300">{project.problem}</p><p className="mt-4 text-sm leading-relaxed text-gray-400"><span className="font-semibold text-gray-200">Approach: </span>{project.approach}</p><div className="mt-5"><p className="mb-2 text-xs font-semibold uppercase tracking-wider text-cyan-200">Stack</p><div className="flex flex-wrap gap-2">{project.stack.map((item) => <span key={item} className="rounded-full border border-blue-400/20 bg-blue-500/10 px-2.5 py-1 text-xs text-blue-100">{item}</span>)}</div></div><ul className="mt-5 space-y-2 text-sm text-gray-400">{project.features.map((feature) => <li key={feature} className="flex gap-2"><span className="text-cyan-300">+</span>{feature}</li>)}</ul><div className="mt-auto flex flex-wrap gap-3 pt-6">{project.demo && <a href={project.demo} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-cyan-500/15 px-3 py-2 text-sm text-cyan-200 hover:bg-cyan-500/25"><ExternalLink size={15} />Live Demo</a>}{project.github && <a href={project.github} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-lg border border-gray-600/60 px-3 py-2 text-sm text-gray-200 hover:border-gray-400"><Github size={15} />GitHub</a>}{project.research && <a href={project.research} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-lg border border-emerald-500/30 px-3 py-2 text-sm text-emerald-200 hover:bg-emerald-500/10">Research</a>}</div></motion.article>;
}
